@startuml Development Workflow
start
partition Preparation {
    :Task stage "New";
    ->Started checking\nthe task ;
    note right: Task is assigned
    :Move task to "Design" stage;
    note: Studying the case
    -> Work is started;
    :Fork task repo branch you are\nworking on to your own branch;
    note right
        Name is <forked_branch>-<git_id>
            <i>e.g. "12.0-cetmix"</i>
        You can create as many branches as you need
        <b><color:red>Never</color></b> push to main branch directly!
    end note
}
while (Task status?) is (Development needed)
    partition Development {
        :Move task to "Development" stage;
        repeat :Coding;
            if (Task is blocked?) then (Yes)
                :Mark task as "Blocked";
                -> Report will be sent\nto Project manager.\nProvide further details by\nlogging "Internal Note";
                :Wait for unblock;
                -> Task is unblocked\nYou will receive\nnotification;
            else (no)
            endif
            -> Some code is ready;
            :Push into own branch;
            -> Log time in Timesheets;
        repeat while(More coding?) is (Yes)
    }
    -> Ready to test some or all;
    partition "Local Testing" {
        :Move task to "Testing" stage;
        repeat :Test your code
            if (Errors found?) then (Yes)
                :Fix code;
            else (No)
            endif
        repeat while(More errors?) is (Yes)
    }
    -> Ready to upload code to repo;
    partition "Pre-delivery" {
        repeat :Check code with pre-commit script
            if (Errors found?) then (Yes)
                :Fix code;
            else (No)
            endif
        repeat while(Code is updated?) is (Yes)

        note right: Use provided script
    }
    partition Delivery {
        -> No;
        :Push into own branch;
        :Make pull request into\n"testing" task sub-branch;
        note right
        Name is <forked_branch>-testing
            <i>e.g. "12.0-testing"</i>
        <b><color:red>Never</color></b> push to main branch directly!
    end note
        if (Test results) then (All tests passed)
            if (Task is 100% completed?) then (Yes)
                :Mark task "Ready for next stage";
                if (Task stage is changed\nby Project Manager) then (Stage "Done")
                    :Task is completed;
                    stop
                else (Stage "Check")
                    :Task is being\nchecked by\nmanager;
                    if (Task) then (Stage changed\nto "Done")
                        :Task is completed;
                        stop
                    else (Marked as "Fix needed")
                        :You will receive feedback;
                    endif
                endif
            else (No)
            endif
        else (Some tests failed)
        endif
    }
endwhile (All done\nNo complains)
:Task will be moved to\n"Done" stage;
stop
@enduml